; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O0 -mtriple=riscv32 -mattr=+xcvbi -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

define i32 @beqimm(i32 %a) {
; CHECK-LABEL: beqimm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.beqimm a0, 5, .LBB0_2
; CHECK-NEXT:    j .LBB0_1
; CHECK-NEXT:  .LBB0_1: # %f
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB0_2: # %t
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    ret
  %1 = icmp eq i32 %a, 5
  br i1 %1, label %t, label %f
f:
  ret i32 0
t:
  ret i32 1
}

define i32 @bneimm(i32 %a) {
; CHECK-LABEL: bneimm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.bneimm a0, 5, .LBB1_2
; CHECK-NEXT:    j .LBB1_1
; CHECK-NEXT:  .LBB1_1: # %f
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB1_2: # %t
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    ret
  %1 = icmp ne i32 %a, 5
  br i1 %1, label %t, label %f
f:
  ret i32 0
t:
  ret i32 1
}
