// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +xcvbitmanip -emit-llvm %s -o - \
// RUN:     | FileCheck %s

#include <stdint.h>
#include <riscv_corev_bitmanip.h>

// CHECK-LABEL: @test_extract
// CHECK: @llvm.riscv.cv.bitmanip.extract
uint32_t test_extract(uint32_t a) {
	return __riscv_cv_bitmanip_extract(a, 0);
}

// CHECK-LABEL: @test_extractr
// CHECK: @llvm.riscv.cv.bitmanip.extract
uint32_t test_extractr(uint32_t a, uint16_t b) {
	return __riscv_cv_bitmanip_extract(a, b);
}

// CHECK-LABEL: @test_extractu
// CHECK: @llvm.riscv.cv.bitmanip.extractu
uint32_t test_extractu(uint32_t a) {
	return __riscv_cv_bitmanip_extractu(a, 0);
}

// CHECK-LABEL: @test_extractur
// CHECK: @llvm.riscv.cv.bitmanip.extractu
uint32_t test_extractur(uint32_t a, uint16_t b) {
	return __riscv_cv_bitmanip_extractu(a, b);
}

// CHECK-LABEL: @test_insert
// CHECK: @llvm.riscv.cv.bitmanip.insert
uint32_t test_insert(uint32_t a, uint32_t c) {
	return __riscv_cv_bitmanip_insert(a, 0, c);
}

// CHECK-LABEL: @test_insertr
// CHECK: @llvm.riscv.cv.bitmanip.insert
uint32_t test_insertr(uint32_t a, uint16_t b, uint32_t c) {
	return __riscv_cv_bitmanip_insert(a, b, c);
}

// CHECK-LABEL: @test_bclr
// CHECK: @llvm.riscv.cv.bitmanip.bclr
uint32_t test_bclr(uint32_t a) {
	return __riscv_cv_bitmanip_bclr(a, 0);
}

// CHECK-LABEL: @test_bclrr
// CHECK: @llvm.riscv.cv.bitmanip.bclr
uint32_t test_bclrr(uint32_t a, uint16_t b) {
	return __riscv_cv_bitmanip_bclr(a, b);
}

// CHECK-LABEL: @test_bset
// CHECK: @llvm.riscv.cv.bitmanip.bset
uint32_t test_bset(uint32_t a) {
	return __riscv_cv_bitmanip_bset(a, 0);
}

// CHECK-LABEL: @test_bsetr
// CHECK: @llvm.riscv.cv.bitmanip.bclr
uint32_t test_bsetr(uint32_t a, uint16_t b) {
	return __riscv_cv_bitmanip_bclr(a, b);
}

// CHECK-LABEL: @test_ff1
// CHECK: @llvm.riscv.cv.bitmanip.ff1
uint32_t test_ff1(uint32_t a) {
    return __riscv_cv_bitmanip_ff1(a);
}

// CHECK-LABEL: @test_fl1
// CHECK: @llvm.riscv.cv.bitmanip.fl1
uint32_t test_fl1(uint32_t a) {
    return __riscv_cv_bitmanip_fl1(a);
}

// CHECK-LABEL: @test_clb
// CHECK: @llvm.riscv.cv.bitmanip.clb
uint32_t test_clb(uint32_t a) {
    return __riscv_cv_bitmanip_clb(a);
}

// CHECK-LABEL: @test_cnt
// CHECK: @llvm.riscv.cv.bitmanip.cnt
uint32_t test_cnt(uint32_t a) {
    return __riscv_cv_bitmanip_cnt(a);
}

// CHECK-LABEL: @test_ror
// CHECK: @llvm.fshr.i32
uint32_t test_ror(uint32_t a, uint32_t b) {
    return __riscv_cv_bitmanip_ror(a, b);
}

// CHECK-LABEL: @test_bitrev
// CHECK: @llvm.riscv.cv.bitmanip.bitrev
uint32_t test_bitrev(uint32_t a) {
    return __riscv_cv_bitmanip_bitrev(a, 1, 2);
}
