// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +xcvelw -emit-llvm %s -o - \
// RUN:     | FileCheck %s


// CHECK-LABEL: @test_elw(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    store ptr [[B:%.*]], ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr i8, ptr [[TMP0]], i32 8
// CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.riscv.cv.elw.elw(ptr [[ADD_PTR]])
// CHECK-NEXT:    ret i32 [[TMP1]]
//
int test_elw(void *b) {
  return __builtin_riscv_cv_elw_elw(b + 8);
}
