// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +xcvsimd -emit-llvm %s -o - \
// RUN:     | FileCheck %s

#include <stdint.h>
#include <riscv_corev_simd.h>

// CHECK-LABEL: @test_add_h
// CHECK: @llvm.riscv.cv.simd.add.h
uint32_t test_add_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_add_h(a, b, 0);
}

// CHECK-LABEL: @test_add_b
// CHECK: @llvm.riscv.cv.simd.add.b
uint32_t test_add_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_add_b(a, b);
}

// CHECK-LABEL: @test_add_sc_h
// CHECK: @llvm.riscv.cv.simd.add.sc.h
uint32_t test_add_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_add_sc_h(a, b);
}

// CHECK-LABEL: @test_add_sci_h
// CHECK: @llvm.riscv.cv.simd.add.sc.h
uint32_t test_add_sci_h(uint32_t a) {
	return __riscv_cv_simd_add_sc_h(a, 0);
}

// CHECK-LABEL: @test_add_sc_b
// CHECK: @llvm.riscv.cv.simd.add.sc.b
uint32_t test_add_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_add_sc_b(a, b);
}

// CHECK-LABEL: @test_add_sci_b
// CHECK: @llvm.riscv.cv.simd.add.sc.b
uint32_t test_add_sci_b(uint32_t a) {
	return __riscv_cv_simd_add_sc_b(a, 0);
}

// CHECK-LABEL: @test_sub_h
// CHECK: @llvm.riscv.cv.simd.sub.h
uint32_t test_sub_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_sub_h(a, b, 0);
}

// CHECK-LABEL: @test_sub_b
// CHECK: @llvm.riscv.cv.simd.sub.b
uint32_t test_sub_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_sub_b(a, b);
}

// CHECK-LABEL: @test_sub_sc_h
// CHECK: @llvm.riscv.cv.simd.sub.sc.h
uint32_t test_sub_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_sub_sc_h(a, b);
}

// CHECK-LABEL: @test_sub_sci_h
// CHECK: @llvm.riscv.cv.simd.sub.sc.h
uint32_t test_sub_sci_h(uint32_t a) {
	return __riscv_cv_simd_sub_sc_h(a, 0);
}

// CHECK-LABEL: @test_sub_sc_b
// CHECK: @llvm.riscv.cv.simd.sub.sc.b
uint32_t test_sub_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_sub_sc_b(a, b);
}

// CHECK-LABEL: @test_sub_sci_b
// CHECK: @llvm.riscv.cv.simd.sub.sc.b
uint32_t test_sub_sci_b(uint32_t a) {
	return __riscv_cv_simd_sub_sc_b(a, 0);
}

// CHECK-LABEL: @test_avg_h
// CHECK: @llvm.riscv.cv.simd.avg.h
uint32_t test_avg_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_avg_h(a, b);
}

// CHECK-LABEL: @test_avg_b
// CHECK: @llvm.riscv.cv.simd.avg.b
uint32_t test_avg_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_avg_b(a, b);
}

// CHECK-LABEL: @test_avg_sc_h
// CHECK: @llvm.riscv.cv.simd.avg.sc.h
uint32_t test_avg_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_avg_sc_h(a, b);
}

// CHECK-LABEL: @test_avg_sci_h
// CHECK: @llvm.riscv.cv.simd.avg.sc.h
uint32_t test_avg_sci_h(uint32_t a) {
	return __riscv_cv_simd_avg_sc_h(a, 0);
}

// CHECK-LABEL: @test_avg_sc_b
// CHECK: @llvm.riscv.cv.simd.avg.sc.b
uint32_t test_avg_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_avg_sc_b(a, b);
}

// CHECK-LABEL: @test_avg_sci_b
// CHECK: @llvm.riscv.cv.simd.avg.sc.b
uint32_t test_avg_sci_b(uint32_t a) {
	return __riscv_cv_simd_avg_sc_b(a, 0);
}

// CHECK-LABEL: @test_avgu_h
// CHECK: @llvm.riscv.cv.simd.avgu.h
uint32_t test_avgu_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_avgu_h(a, b);
}

// CHECK-LABEL: @test_avgu_b
// CHECK: @llvm.riscv.cv.simd.avgu.b
uint32_t test_avgu_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_avgu_b(a, b);
}

// CHECK-LABEL: @test_avgu_sc_h
// CHECK: @llvm.riscv.cv.simd.avgu.sc.h
uint32_t test_avgu_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_avgu_sc_h(a, b);
}

// CHECK-LABEL: @test_avgu_sci_h
// CHECK: @llvm.riscv.cv.simd.avgu.sc.h
uint32_t test_avgu_sci_h(uint32_t a) {
	return __riscv_cv_simd_avgu_sc_h(a, 0);
}

// CHECK-LABEL: @test_avgu_sc_b
// CHECK: @llvm.riscv.cv.simd.avgu.sc.b
uint32_t test_avgu_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_avgu_sc_b(a, b);
}

// CHECK-LABEL: @test_avgu_sci_b
// CHECK: @llvm.riscv.cv.simd.avgu.sc.b
uint32_t test_avgu_sci_b(uint32_t a) {
	return __riscv_cv_simd_avgu_sc_b(a, 0);
}

// CHECK-LABEL: @test_min_h
// CHECK: @llvm.riscv.cv.simd.min.h
uint32_t test_min_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_min_h(a, b);
}

// CHECK-LABEL: @test_min_b
// CHECK: @llvm.riscv.cv.simd.min.b
uint32_t test_min_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_min_b(a, b);
}

// CHECK-LABEL: @test_min_sc_h
// CHECK: @llvm.riscv.cv.simd.min.sc.h
uint32_t test_min_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_min_sc_h(a, b);
}

// CHECK-LABEL: @test_min_sci_h
// CHECK: @llvm.riscv.cv.simd.min.sc.h
uint32_t test_min_sci_h(uint32_t a) {
	return __riscv_cv_simd_min_sc_h(a, 0);
}

// CHECK-LABEL: @test_min_sc_b
// CHECK: @llvm.riscv.cv.simd.min.sc.b
uint32_t test_min_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_min_sc_b(a, b);
}

// CHECK-LABEL: @test_min_sci_b
// CHECK: @llvm.riscv.cv.simd.min.sc.b
uint32_t test_min_sci_b(uint32_t a) {
	return __riscv_cv_simd_min_sc_b(a, 0);
}

// CHECK-LABEL: @test_minu_h
// CHECK: @llvm.riscv.cv.simd.minu.h
uint32_t test_minu_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_minu_h(a, b);
}

// CHECK-LABEL: @test_minu_b
// CHECK: @llvm.riscv.cv.simd.minu.b
uint32_t test_minu_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_minu_b(a, b);
}

// CHECK-LABEL: @test_minu_sc_h
// CHECK: @llvm.riscv.cv.simd.minu.sc.h
uint32_t test_minu_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_minu_sc_h(a, b);
}

// CHECK-LABEL: @test_minu_sci_h
// CHECK: @llvm.riscv.cv.simd.minu.sc.h
uint32_t test_minu_sci_h(uint32_t a) {
	return __riscv_cv_simd_minu_sc_h(a, 0);
}

// CHECK-LABEL: @test_minu_sc_b
// CHECK: @llvm.riscv.cv.simd.minu.sc.b
uint32_t test_minu_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_minu_sc_b(a, b);
}

// CHECK-LABEL: @test_minu_sci_b
// CHECK: @llvm.riscv.cv.simd.minu.sc.b
uint32_t test_minu_sci_b(uint32_t a) {
	return __riscv_cv_simd_minu_sc_b(a, 0);
}

// CHECK-LABEL: @test_max_h
// CHECK: @llvm.riscv.cv.simd.max.h
uint32_t test_max_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_max_h(a, b);
}

// CHECK-LABEL: @test_max_b
// CHECK: @llvm.riscv.cv.simd.max.b
uint32_t test_max_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_max_b(a, b);
}

// CHECK-LABEL: @test_max_sc_h
// CHECK: @llvm.riscv.cv.simd.max.sc.h
uint32_t test_max_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_max_sc_h(a, b);
}

// CHECK-LABEL: @test_max_sci_h
// CHECK: @llvm.riscv.cv.simd.max.sc.h
uint32_t test_max_sci_h(uint32_t a) {
	return __riscv_cv_simd_max_sc_h(a, 0);
}

// CHECK-LABEL: @test_max_sc_b
// CHECK: @llvm.riscv.cv.simd.max.sc.b
uint32_t test_max_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_max_sc_b(a, b);
}

// CHECK-LABEL: @test_max_sci_b
// CHECK: @llvm.riscv.cv.simd.max.sc.b
uint32_t test_max_sci_b(uint32_t a) {
	return __riscv_cv_simd_max_sc_b(a, 0);
}

// CHECK-LABEL: @test_maxu_h
// CHECK: @llvm.riscv.cv.simd.maxu.h
uint32_t test_maxu_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_maxu_h(a, b);
}

// CHECK-LABEL: @test_maxu_b
// CHECK: @llvm.riscv.cv.simd.maxu.b
uint32_t test_maxu_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_maxu_b(a, b);
}

// CHECK-LABEL: @test_maxu_sc_h
// CHECK: @llvm.riscv.cv.simd.maxu.sc.h
uint32_t test_maxu_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_maxu_sc_h(a, b);
}

// CHECK-LABEL: @test_maxu_sci_h
// CHECK: @llvm.riscv.cv.simd.maxu.sc.h
uint32_t test_maxu_sci_h(uint32_t a) {
	return __riscv_cv_simd_maxu_sc_h(a, 0);
}

// CHECK-LABEL: @test_maxu_sc_b
// CHECK: @llvm.riscv.cv.simd.maxu.sc.b
uint32_t test_maxu_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_maxu_sc_b(a, b);
}

// CHECK-LABEL: @test_maxu_sci_b
// CHECK: @llvm.riscv.cv.simd.maxu.sc.b
uint32_t test_maxu_sci_b(uint32_t a) {
	return __riscv_cv_simd_maxu_sc_b(a, 0);
}

// CHECK-LABEL: @test_srl_h
// CHECK: @llvm.riscv.cv.simd.srl.h
uint32_t test_srl_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_srl_h(a, b);
}

// CHECK-LABEL: @test_srl_b
// CHECK: @llvm.riscv.cv.simd.srl.b
uint32_t test_srl_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_srl_b(a, b);
}

// CHECK-LABEL: @test_srl_sc_h
// CHECK: @llvm.riscv.cv.simd.srl.sc.h
uint32_t test_srl_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_srl_sc_h(a, b);
}

// CHECK-LABEL: @test_srl_sci_h
// CHECK: @llvm.riscv.cv.simd.srl.sc.h
uint32_t test_srl_sci_h(uint32_t a) {
	return __riscv_cv_simd_srl_sc_h(a, 0);
}

// CHECK-LABEL: @test_srl_sc_b
// CHECK: @llvm.riscv.cv.simd.srl.sc.b
uint32_t test_srl_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_srl_sc_b(a, b);
}

// CHECK-LABEL: @test_srl_sci_b
// CHECK: @llvm.riscv.cv.simd.srl.sc.b
uint32_t test_srl_sci_b(uint32_t a) {
	return __riscv_cv_simd_srl_sc_b(a, 0);
}

// CHECK-LABEL: @test_sra_h
// CHECK: @llvm.riscv.cv.simd.sra.h
uint32_t test_sra_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_sra_h(a, b);
}

// CHECK-LABEL: @test_sra_b
// CHECK: @llvm.riscv.cv.simd.sra.b
uint32_t test_sra_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_sra_b(a, b);
}

// CHECK-LABEL: @test_sra_sc_h
// CHECK: @llvm.riscv.cv.simd.sra.sc.h
uint32_t test_sra_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_sra_sc_h(a, b);
}

// CHECK-LABEL: @test_sra_sci_h
// CHECK: @llvm.riscv.cv.simd.sra.sc.h
uint32_t test_sra_sci_h(uint32_t a) {
	return __riscv_cv_simd_sra_sc_h(a, 0);
}

// CHECK-LABEL: @test_sra_sc_b
// CHECK: @llvm.riscv.cv.simd.sra.sc.b
uint32_t test_sra_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_sra_sc_b(a, b);
}

// CHECK-LABEL: @test_sra_sci_b
// CHECK: @llvm.riscv.cv.simd.sra.sc.b
uint32_t test_sra_sci_b(uint32_t a) {
	return __riscv_cv_simd_sra_sc_b(a, 0);
}

// CHECK-LABEL: @test_sll_h
// CHECK: @llvm.riscv.cv.simd.sll.h
uint32_t test_sll_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_sll_h(a, b);
}

// CHECK-LABEL: @test_sll_b
// CHECK: @llvm.riscv.cv.simd.sll.b
uint32_t test_sll_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_sll_b(a, b);
}

// CHECK-LABEL: @test_sll_sc_h
// CHECK: @llvm.riscv.cv.simd.sll.sc.h
uint32_t test_sll_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_sll_sc_h(a, b);
}

// CHECK-LABEL: @test_sll_sci_h
// CHECK: @llvm.riscv.cv.simd.sll.sc.h
uint32_t test_sll_sci_h(uint32_t a) {
	return __riscv_cv_simd_sll_sc_h(a, 0);
}

// CHECK-LABEL: @test_sll_sc_b
// CHECK: @llvm.riscv.cv.simd.sll.sc.b
uint32_t test_sll_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_sll_sc_b(a, b);
}

// CHECK-LABEL: @test_sll_sci_b
// CHECK: @llvm.riscv.cv.simd.sll.sc.b
uint32_t test_sll_sci_b(uint32_t a) {
	return __riscv_cv_simd_sll_sc_b(a, 0);
}

// CHECK-LABEL: @test_or_h
// CHECK: @llvm.riscv.cv.simd.or.h
uint32_t test_or_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_or_h(a, b);
}

// CHECK-LABEL: @test_or_b
// CHECK: @llvm.riscv.cv.simd.or.b
uint32_t test_or_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_or_b(a, b);
}

// CHECK-LABEL: @test_or_sc_h
// CHECK: @llvm.riscv.cv.simd.or.sc.h
uint32_t test_or_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_or_sc_h(a, b);
}

// CHECK-LABEL: @test_or_sci_h
// CHECK: @llvm.riscv.cv.simd.or.sc.h
uint32_t test_or_sci_h(uint32_t a) {
	return __riscv_cv_simd_or_sc_h(a, 0);
}

// CHECK-LABEL: @test_or_sc_b
// CHECK: @llvm.riscv.cv.simd.or.sc.b
uint32_t test_or_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_or_sc_b(a, b);
}

// CHECK-LABEL: @test_or_sci_b
// CHECK: @llvm.riscv.cv.simd.or.sc.b
uint32_t test_or_sci_b(uint32_t a) {
	return __riscv_cv_simd_or_sc_b(a, 0);
}

// CHECK-LABEL: @test_xor_h
// CHECK: @llvm.riscv.cv.simd.xor.h
uint32_t test_xor_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_xor_h(a, b);
}

// CHECK-LABEL: @test_xor_b
// CHECK: @llvm.riscv.cv.simd.xor.b
uint32_t test_xor_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_xor_b(a, b);
}

// CHECK-LABEL: @test_xor_sc_h
// CHECK: @llvm.riscv.cv.simd.xor.sc.h
uint32_t test_xor_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_xor_sc_h(a, b);
}

// CHECK-LABEL: @test_xor_sci_h
// CHECK: @llvm.riscv.cv.simd.xor.sc.h
uint32_t test_xor_sci_h(uint32_t a) {
	return __riscv_cv_simd_xor_sc_h(a, 0);
}

// CHECK-LABEL: @test_xor_sc_b
// CHECK: @llvm.riscv.cv.simd.xor.sc.b
uint32_t test_xor_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_xor_sc_b(a, b);
}

// CHECK-LABEL: @test_xor_sci_b
// CHECK: @llvm.riscv.cv.simd.xor.sc.b
uint32_t test_xor_sci_b(uint32_t a) {
	return __riscv_cv_simd_xor_sc_b(a, 0);
}

// CHECK-LABEL: @test_and_h
// CHECK: @llvm.riscv.cv.simd.and.h
uint32_t test_and_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_and_h(a, b);
}

// CHECK-LABEL: @test_and_b
// CHECK: @llvm.riscv.cv.simd.and.b
uint32_t test_and_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_and_b(a, b);
}

// CHECK-LABEL: @test_and_sc_h
// CHECK: @llvm.riscv.cv.simd.and.sc.h
uint32_t test_and_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_and_sc_h(a, b);
}

// CHECK-LABEL: @test_and_sci_h
// CHECK: @llvm.riscv.cv.simd.and.sc.h
uint32_t test_and_sci_h(uint32_t a) {
	return __riscv_cv_simd_and_sc_h(a, 0);
}

// CHECK-LABEL: @test_and_sc_b
// CHECK: @llvm.riscv.cv.simd.and.sc.b
uint32_t test_and_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_and_sc_b(a, b);
}

// CHECK-LABEL: @test_and_sci_b
// CHECK: @llvm.riscv.cv.simd.and.sc.b
uint32_t test_and_sci_b(uint32_t a) {
	return __riscv_cv_simd_and_sc_b(a, 0);
}

// CHECK-LABEL: @test_abs_h
// CHECK: @llvm.riscv.cv.simd.abs.h
uint32_t test_abs_h(uint32_t a) {
	return __riscv_cv_simd_abs_h(a);
}

// CHECK-LABEL: @test_abs_b
// CHECK: @llvm.riscv.cv.simd.abs.b
uint32_t test_abs_b(uint32_t a) {
	return __riscv_cv_simd_abs_b(a);
}

// CHECK-LABEL: @test_neg_h
// CHECK: @llvm.riscv.cv.simd.sub.h
uint32_t test_neg_h(uint32_t a) {
	return __riscv_cv_simd_neg_h(a);
}

// CHECK-LABEL: @test_neg_b
// CHECK: @llvm.riscv.cv.simd.sub.b
uint32_t test_neg_b(uint32_t a) {
	return __riscv_cv_simd_neg_b(a);
}

// CHECK-LABEL: @test_dotup_h
// CHECK: @llvm.riscv.cv.simd.dotup.h
uint32_t test_dotup_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_dotup_h(a, b);
}

// CHECK-LABEL: @test_dotup_b
// CHECK: @llvm.riscv.cv.simd.dotup.b
uint32_t test_dotup_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_dotup_b(a, b);
}

// CHECK-LABEL: @test_dotup_sc_h
// CHECK: @llvm.riscv.cv.simd.dotup.sc.h
uint32_t test_dotup_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_dotup_sc_h(a, b);
}

// CHECK-LABEL: @test_dotup_sci_h
// CHECK: @llvm.riscv.cv.simd.dotup.sc.h
uint32_t test_dotup_sci_h(uint32_t a) {
	return __riscv_cv_simd_dotup_sc_h(a, 0);
}

// CHECK-LABEL: @test_dotup_sc_b
// CHECK: @llvm.riscv.cv.simd.dotup.sc.b
uint32_t test_dotup_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_dotup_sc_b(a, b);
}

// CHECK-LABEL: @test_dotup_sci_b
// CHECK: @llvm.riscv.cv.simd.dotup.sc.b
uint32_t test_dotup_sci_b(uint32_t a) {
	return __riscv_cv_simd_dotup_sc_b(a, 0);
}

// CHECK-LABEL: @test_dotusp_h
// CHECK: @llvm.riscv.cv.simd.dotusp.h
uint32_t test_dotusp_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_dotusp_h(a, b);
}

// CHECK-LABEL: @test_dotusp_b
// CHECK: @llvm.riscv.cv.simd.dotusp.b
uint32_t test_dotusp_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_dotusp_b(a, b);
}

// CHECK-LABEL: @test_dotusp_sc_h
// CHECK: @llvm.riscv.cv.simd.dotusp.sc.h
uint32_t test_dotusp_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_dotusp_sc_h(a, b);
}

// CHECK-LABEL: @test_dotusp_sci_h
// CHECK: @llvm.riscv.cv.simd.dotusp.sc.h
uint32_t test_dotusp_sci_h(uint32_t a) {
	return __riscv_cv_simd_dotusp_sc_h(a, 0);
}

// CHECK-LABEL: @test_dotusp_sc_b
// CHECK: @llvm.riscv.cv.simd.dotusp.sc.b
uint32_t test_dotusp_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_dotusp_sc_b(a, b);
}

// CHECK-LABEL: @test_dotusp_sci_b
// CHECK: @llvm.riscv.cv.simd.dotusp.sc.b
uint32_t test_dotusp_sci_b(uint32_t a) {
	return __riscv_cv_simd_dotusp_sc_b(a, 0);
}

// CHECK-LABEL: @test_dotsp_h
// CHECK: @llvm.riscv.cv.simd.dotsp.h
uint32_t test_dotsp_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_dotsp_h(a, b);
}

// CHECK-LABEL: @test_dotsp_b
// CHECK: @llvm.riscv.cv.simd.dotsp.b
uint32_t test_dotsp_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_dotsp_b(a, b);
}

// CHECK-LABEL: @test_dotsp_sc_h
// CHECK: @llvm.riscv.cv.simd.dotsp.sc.h
uint32_t test_dotsp_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_dotsp_sc_h(a, b);
}

// CHECK-LABEL: @test_dotsp_sci_h
// CHECK: @llvm.riscv.cv.simd.dotsp.sc.h
uint32_t test_dotsp_sci_h(uint32_t a) {
	return __riscv_cv_simd_dotsp_sc_h(a, 0);
}

// CHECK-LABEL: @test_dotsp_sc_b
// CHECK: @llvm.riscv.cv.simd.dotsp.sc.b
uint32_t test_dotsp_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_dotsp_sc_b(a, b);
}

// CHECK-LABEL: @test_dotsp_sci_b
// CHECK: @llvm.riscv.cv.simd.dotsp.sc.b
uint32_t test_dotsp_sci_b(uint32_t a) {
	return __riscv_cv_simd_dotsp_sc_b(a, 0);
}

// CHECK-LABEL: @test_sdotup_h
// CHECK: @llvm.riscv.cv.simd.sdotup.h
uint32_t test_sdotup_h(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_sdotup_h(a, b, c);
}

// CHECK-LABEL: @test_sdotup_b
// CHECK: @llvm.riscv.cv.simd.sdotup.b
uint32_t test_sdotup_b(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_sdotup_b(a, b, c);
}

// CHECK-LABEL: @test_sdotup_sc_h
// CHECK: @llvm.riscv.cv.simd.sdotup.sc.h
uint32_t test_sdotup_sc_h(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_sdotup_sc_h(a, b, c);
}

// CHECK-LABEL: @test_sdotup_sci_h
// CHECK: @llvm.riscv.cv.simd.sdotup.sc.h
uint32_t test_sdotup_sci_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_sdotup_sc_h(a, 0, b);
}

// CHECK-LABEL: @test_sdotup_sc_b
// CHECK: @llvm.riscv.cv.simd.sdotup.sc.b
uint32_t test_sdotup_sc_b(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_sdotup_sc_b(a, b, c);
}

// CHECK-LABEL: @test_sdotup_sci_b
// CHECK: @llvm.riscv.cv.simd.sdotup.sc.b
uint32_t test_sdotup_sci_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_sdotup_sc_b(a, 0, b);
}

// CHECK-LABEL: @test_sdotusp_h
// CHECK: @llvm.riscv.cv.simd.sdotusp.h
uint32_t test_sdotusp_h(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_sdotusp_h(a, b, c);
}

// CHECK-LABEL: @test_sdotusp_b
// CHECK: @llvm.riscv.cv.simd.sdotusp.b
uint32_t test_sdotusp_b(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_sdotusp_b(a, b, c);
}

// CHECK-LABEL: @test_sdotusp_sc_h
// CHECK: @llvm.riscv.cv.simd.sdotusp.sc.h
uint32_t test_sdotusp_sc_h(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_sdotusp_sc_h(a, b, c);
}

// CHECK-LABEL: @test_sdotusp_sci_h
// CHECK: @llvm.riscv.cv.simd.sdotusp.sc.h
uint32_t test_sdotusp_sci_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_sdotusp_sc_h(a, 0, b);
}

// CHECK-LABEL: @test_sdotusp_sc_b
// CHECK: @llvm.riscv.cv.simd.sdotusp.sc.b
uint32_t test_sdotusp_sc_b(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_sdotusp_sc_b(a, b, c);
}

// CHECK-LABEL: @test_sdotusp_sci_b
// CHECK: @llvm.riscv.cv.simd.sdotusp.sc.b
uint32_t test_sdotusp_sci_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_sdotusp_sc_b(a, 0, b);
}

// CHECK-LABEL: @test_sdotsp_h
// CHECK: @llvm.riscv.cv.simd.sdotsp.h
uint32_t test_sdotsp_h(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_sdotsp_h(a, b, c);
}

// CHECK-LABEL: @test_sdotsp_b
// CHECK: @llvm.riscv.cv.simd.sdotsp.b
uint32_t test_sdotsp_b(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_sdotsp_b(a, b, c);
}

// CHECK-LABEL: @test_sdotsp_sc_h
// CHECK: @llvm.riscv.cv.simd.sdotsp.sc.h
uint32_t test_sdotsp_sc_h(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_sdotsp_sc_h(a, b, c);
}

// CHECK-LABEL: @test_sdotsp_sci_h
// CHECK: @llvm.riscv.cv.simd.sdotsp.sc.h
uint32_t test_sdotsp_sci_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_sdotsp_sc_h(a, 0, b);
}

// CHECK-LABEL: @test_sdotsp_sc_b
// CHECK: @llvm.riscv.cv.simd.sdotsp.sc.b
uint32_t test_sdotsp_sc_b(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_sdotsp_sc_b(a, b, c);
}

// CHECK-LABEL: @test_sdotsp_sci_b
// CHECK: @llvm.riscv.cv.simd.sdotsp.sc.b
uint32_t test_sdotsp_sci_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_sdotsp_sc_b(a, 0, b);
}

// CHECK-LABEL: @test_extract_h
// CHECK: @llvm.riscv.cv.simd.extract.h
uint32_t test_extract_h(uint32_t a) {
	return __riscv_cv_simd_extract_h(a, 0);
}

// CHECK-LABEL: @test_extract_b
// CHECK: @llvm.riscv.cv.simd.extract.b
uint32_t test_extract_b(uint32_t a) {
	return __riscv_cv_simd_extract_b(a, 0);
}

// CHECK-LABEL: @test_extractu_h
// CHECK: @llvm.riscv.cv.simd.extractu.h
uint32_t test_extractu_h(uint32_t a) {
	return __riscv_cv_simd_extractu_h(a, 0);
}

// CHECK-LABEL: @test_extractu_b
// CHECK: @llvm.riscv.cv.simd.extractu.b
uint32_t test_extractu_b(uint32_t a) {
	return __riscv_cv_simd_extractu_b(a, 0);
}

// CHECK-LABEL: @test_shuffle_h
// CHECK: @llvm.riscv.cv.simd.shuffle.h
uint32_t test_shuffle_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_shuffle_h(a, b);
}

// CHECK-LABEL: @test_shuffle_b
// CHECK: @llvm.riscv.cv.simd.shuffle.b
uint32_t test_shuffle_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_shuffle_b(a, b);
}

// CHECK-LABEL: @test_shuffle_sci_h
// CHECK: @llvm.riscv.cv.simd.shuffle.sci.h
uint32_t test_shuffle_sci_h(uint32_t a) {
	return __riscv_cv_simd_shuffle_sci_h(a, 0);
}

// CHECK-LABEL: @test_shuffleI0_sci_b
// CHECK: @llvm.riscv.cv.simd.shuffle.sci.b
uint32_t test_shuffleI0_sci_b(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_shuffle_sci_b(a, 0);
}

// CHECK-LABEL: @test_shuffle2_h
// CHECK: @llvm.riscv.cv.simd.shuffle2.h
uint32_t test_shuffle2_h(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_shuffle2_h(a, b, c);
}

// CHECK-LABEL: @test_shuffle2_b
// CHECK: @llvm.riscv.cv.simd.shuffle2.b
uint32_t test_shuffle2_b(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_shuffle2_b(a, b, c);
}

// CHECK-LABEL: @test_packhi_h
// CHECK: @llvm.riscv.cv.simd.packhi.h
uint32_t test_packhi_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_packhi_h(a, b);
}

// CHECK-LABEL: @test_packlo_h
// CHECK: @llvm.riscv.cv.simd.packlo.h
uint32_t test_packlo_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_packlo_h(a, b);
}

// CHECK-LABEL: @test_cmpeq_h
// CHECK: @llvm.riscv.cv.simd.cmpeq.h
uint32_t test_cmpeq_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmpeq_h(a, b);
}

// CHECK-LABEL: @test_cmpeq_b
// CHECK: @llvm.riscv.cv.simd.cmpeq.b
uint32_t test_cmpeq_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmpeq_b(a, b);
}

// CHECK-LABEL: @test_cmpeq_sc_h
// CHECK: @llvm.riscv.cv.simd.cmpeq.sc.h
uint32_t test_cmpeq_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_cmpeq_sc_h(a, b);
}

// CHECK-LABEL: @test_cmpeq_sci_h
// CHECK: @llvm.riscv.cv.simd.cmpeq.sc.h
uint32_t test_cmpeq_sci_h(uint32_t a) {
	return __riscv_cv_simd_cmpeq_sc_h(a, 0);
}

// CHECK-LABEL: @test_cmpeq_sc_b
// CHECK: @llvm.riscv.cv.simd.cmpeq.sc.b
uint32_t test_cmpeq_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_cmpeq_sc_b(a, b);
}

// CHECK-LABEL: @test_cmpeq_sci_b
// CHECK: @llvm.riscv.cv.simd.cmpeq.sc.b
uint32_t test_cmpeq_sci_b(uint32_t a) {
	return __riscv_cv_simd_cmpeq_sc_b(a, 0);
}

// CHECK-LABEL: @test_cmpne_h
// CHECK: @llvm.riscv.cv.simd.cmpne.h
uint32_t test_cmpne_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmpne_h(a, b);
}

// CHECK-LABEL: @test_cmpne_b
// CHECK: @llvm.riscv.cv.simd.cmpne.b
uint32_t test_cmpne_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmpne_b(a, b);
}

// CHECK-LABEL: @test_cmpne_sc_h
// CHECK: @llvm.riscv.cv.simd.cmpne.sc.h
uint32_t test_cmpne_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_cmpne_sc_h(a, b);
}

// CHECK-LABEL: @test_cmpne_sci_h
// CHECK: @llvm.riscv.cv.simd.cmpne.sc.h
uint32_t test_cmpne_sci_h(uint32_t a) {
	return __riscv_cv_simd_cmpne_sc_h(a, 0);
}

// CHECK-LABEL: @test_cmpne_sc_b
// CHECK: @llvm.riscv.cv.simd.cmpne.sc.b
uint32_t test_cmpne_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_cmpne_sc_b(a, b);
}

// CHECK-LABEL: @test_cmpne_sci_b
// CHECK: @llvm.riscv.cv.simd.cmpne.sc.b
uint32_t test_cmpne_sci_b(uint32_t a) {
	return __riscv_cv_simd_cmpne_sc_b(a, 0);
}

// CHECK-LABEL: @test_cmpgt_h
// CHECK: @llvm.riscv.cv.simd.cmpgt.h
uint32_t test_cmpgt_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmpgt_h(a, b);
}

// CHECK-LABEL: @test_cmpgt_b
// CHECK: @llvm.riscv.cv.simd.cmpgt.b
uint32_t test_cmpgt_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmpgt_b(a, b);
}

// CHECK-LABEL: @test_cmpgt_sc_h
// CHECK: @llvm.riscv.cv.simd.cmpgt.sc.h
uint32_t test_cmpgt_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_cmpgt_sc_h(a, b);
}

// CHECK-LABEL: @test_cmpgt_sci_h
// CHECK: @llvm.riscv.cv.simd.cmpgt.sc.h
uint32_t test_cmpgt_sci_h(uint32_t a) {
	return __riscv_cv_simd_cmpgt_sc_h(a, 0);
}

// CHECK-LABEL: @test_cmpgt_sc_b
// CHECK: @llvm.riscv.cv.simd.cmpgt.sc.b
uint32_t test_cmpgt_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_cmpgt_sc_b(a, b);
}

// CHECK-LABEL: @test_cmpgt_sci_b
// CHECK: @llvm.riscv.cv.simd.cmpgt.sc.b
uint32_t test_cmpgt_sci_b(uint32_t a) {
	return __riscv_cv_simd_cmpgt_sc_b(a, 0);
}

// CHECK-LABEL: @test_cmpge_h
// CHECK: @llvm.riscv.cv.simd.cmpge.h
uint32_t test_cmpge_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmpge_h(a, b);
}

// CHECK-LABEL: @test_cmpge_b
// CHECK: @llvm.riscv.cv.simd.cmpge.b
uint32_t test_cmpge_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmpge_b(a, b);
}

// CHECK-LABEL: @test_cmpge_sc_h
// CHECK: @llvm.riscv.cv.simd.cmpge.sc.h
uint32_t test_cmpge_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_cmpge_sc_h(a, b);
}

// CHECK-LABEL: @test_cmpge_sci_h
// CHECK: @llvm.riscv.cv.simd.cmpge.sc.h
uint32_t test_cmpge_sci_h(uint32_t a) {
	return __riscv_cv_simd_cmpge_sc_h(a, 0);
}

// CHECK-LABEL: @test_cmpge_sc_b
// CHECK: @llvm.riscv.cv.simd.cmpge.sc.b
uint32_t test_cmpge_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_cmpge_sc_b(a, b);
}

// CHECK-LABEL: @test_cmpge_sci_b
// CHECK: @llvm.riscv.cv.simd.cmpge.sc.b
uint32_t test_cmpge_sci_b(uint32_t a) {
	return __riscv_cv_simd_cmpge_sc_b(a, 0);
}

// CHECK-LABEL: @test_cmplt_h
// CHECK: @llvm.riscv.cv.simd.cmplt.h
uint32_t test_cmplt_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmplt_h(a, b);
}

// CHECK-LABEL: @test_cmplt_b
// CHECK: @llvm.riscv.cv.simd.cmplt.b
uint32_t test_cmplt_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmplt_b(a, b);
}

// CHECK-LABEL: @test_cmplt_sc_h
// CHECK: @llvm.riscv.cv.simd.cmplt.sc.h
uint32_t test_cmplt_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_cmplt_sc_h(a, b);
}

// CHECK-LABEL: @test_cmplt_sci_h
// CHECK: @llvm.riscv.cv.simd.cmplt.sc.h
uint32_t test_cmplt_sci_h(uint32_t a) {
	return __riscv_cv_simd_cmplt_sc_h(a, 0);
}

// CHECK-LABEL: @test_cmplt_sc_b
// CHECK: @llvm.riscv.cv.simd.cmplt.sc.b
uint32_t test_cmplt_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_cmplt_sc_b(a, b);
}

// CHECK-LABEL: @test_cmplt_sci_b
// CHECK: @llvm.riscv.cv.simd.cmplt.sc.b
uint32_t test_cmplt_sci_b(uint32_t a) {
	return __riscv_cv_simd_cmplt_sc_b(a, 0);
}

// CHECK-LABEL: @test_cmple_h
// CHECK: @llvm.riscv.cv.simd.cmple.h
uint32_t test_cmple_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmple_h(a, b);
}

// CHECK-LABEL: @test_cmple_b
// CHECK: @llvm.riscv.cv.simd.cmple.b
uint32_t test_cmple_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmple_b(a, b);
}

// CHECK-LABEL: @test_cmple_sc_h
// CHECK: @llvm.riscv.cv.simd.cmple.sc.h
uint32_t test_cmple_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_cmple_sc_h(a, b);
}

// CHECK-LABEL: @test_cmple_sci_h
// CHECK: @llvm.riscv.cv.simd.cmple.sc.h
uint32_t test_cmple_sci_h(uint32_t a) {
	return __riscv_cv_simd_cmple_sc_h(a, 0);
}

// CHECK-LABEL: @test_cmple_sc_b
// CHECK: @llvm.riscv.cv.simd.cmple.sc.b
uint32_t test_cmple_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_cmple_sc_b(a, b);
}

// CHECK-LABEL: @test_cmple_sci_b
// CHECK: @llvm.riscv.cv.simd.cmple.sc.b
uint32_t test_cmple_sci_b(uint32_t a) {
	return __riscv_cv_simd_cmple_sc_b(a, 0);
}

// CHECK-LABEL: @test_cmpgtu_h
// CHECK: @llvm.riscv.cv.simd.cmpgtu.h
uint32_t test_cmpgtu_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmpgtu_h(a, b);
}

// CHECK-LABEL: @test_cmpgtu_b
// CHECK: @llvm.riscv.cv.simd.cmpgtu.b
uint32_t test_cmpgtu_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmpgtu_b(a, b);
}

// CHECK-LABEL: @test_cmpgtu_sc_h
// CHECK: @llvm.riscv.cv.simd.cmpgtu.sc.h
uint32_t test_cmpgtu_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_cmpgtu_sc_h(a, b);
}

// CHECK-LABEL: @test_cmpgtu_sci_h
// CHECK: @llvm.riscv.cv.simd.cmpgtu.sc.h
uint32_t test_cmpgtu_sci_h(uint32_t a) {
	return __riscv_cv_simd_cmpgtu_sc_h(a, 0);
}

// CHECK-LABEL: @test_cmpgtu_sc_b
// CHECK: @llvm.riscv.cv.simd.cmpgtu.sc.b
uint32_t test_cmpgtu_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_cmpgtu_sc_b(a, b);
}

// CHECK-LABEL: @test_cmpgtu_sci_b
// CHECK: @llvm.riscv.cv.simd.cmpgtu.sc.b
uint32_t test_cmpgtu_sci_b(uint32_t a) {
	return __riscv_cv_simd_cmpgtu_sc_b(a, 0);
}

// CHECK-LABEL: @test_cmpgeu_h
// CHECK: @llvm.riscv.cv.simd.cmpgeu.h
uint32_t test_cmpgeu_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmpgeu_h(a, b);
}

// CHECK-LABEL: @test_cmpgeu_b
// CHECK: @llvm.riscv.cv.simd.cmpgeu.b
uint32_t test_cmpgeu_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmpgeu_b(a, b);
}

// CHECK-LABEL: @test_cmpgeu_sc_h
// CHECK: @llvm.riscv.cv.simd.cmpgeu.sc.h
uint32_t test_cmpgeu_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_cmpgeu_sc_h(a, b);
}

// CHECK-LABEL: @test_cmpgeu_sci_h
// CHECK: @llvm.riscv.cv.simd.cmpgeu.sc.h
uint32_t test_cmpgeu_sci_h(uint32_t a) {
	return __riscv_cv_simd_cmpgeu_sc_h(a, 0);
}

// CHECK-LABEL: @test_cmpgeu_sc_b
// CHECK: @llvm.riscv.cv.simd.cmpgeu.sc.b
uint32_t test_cmpgeu_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_cmpgeu_sc_b(a, b);
}

// CHECK-LABEL: @test_cmpgeu_sci_b
// CHECK: @llvm.riscv.cv.simd.cmpgeu.sc.b
uint32_t test_cmpgeu_sci_b(uint32_t a) {
	return __riscv_cv_simd_cmpgeu_sc_b(a, 0);
}

// CHECK-LABEL: @test_cmpltu_h
// CHECK: @llvm.riscv.cv.simd.cmpltu.h
uint32_t test_cmpltu_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmpltu_h(a, b);
}

// CHECK-LABEL: @test_cmpltu_b
// CHECK: @llvm.riscv.cv.simd.cmpltu.b
uint32_t test_cmpltu_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmpltu_b(a, b);
}

// CHECK-LABEL: @test_cmpltu_sc_h
// CHECK: @llvm.riscv.cv.simd.cmpltu.sc.h
uint32_t test_cmpltu_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_cmpltu_sc_h(a, b);
}

// CHECK-LABEL: @test_cmpltu_sci_h
// CHECK: @llvm.riscv.cv.simd.cmpltu.sc.h
uint32_t test_cmpltu_sci_h(uint32_t a) {
	return __riscv_cv_simd_cmpltu_sc_h(a, 0);
}

// CHECK-LABEL: @test_cmpltu_sc_b
// CHECK: @llvm.riscv.cv.simd.cmpltu.sc.b
uint32_t test_cmpltu_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_cmpltu_sc_b(a, b);
}

// CHECK-LABEL: @test_cmpltu_sci_b
// CHECK: @llvm.riscv.cv.simd.cmpltu.sc.b
uint32_t test_cmpltu_sci_b(uint32_t a) {
	return __riscv_cv_simd_cmpltu_sc_b(a, 0);
}

// CHECK-LABEL: @test_cmpleu_h
// CHECK: @llvm.riscv.cv.simd.cmpleu.h
uint32_t test_cmpleu_h(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmpleu_h(a, b);
}

// CHECK-LABEL: @test_cmpleu_b
// CHECK: @llvm.riscv.cv.simd.cmpleu.b
uint32_t test_cmpleu_b(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_cmpleu_b(a, b);
}

// CHECK-LABEL: @test_cmpleu_sc_h
// CHECK: @llvm.riscv.cv.simd.cmpleu.sc.h
uint32_t test_cmpleu_sc_h(uint32_t a, uint16_t b) {
	return __riscv_cv_simd_cmpleu_sc_h(a, b);
}

// CHECK-LABEL: @test_cmpleu_sci_h
// CHECK: @llvm.riscv.cv.simd.cmpleu.sc.h
uint32_t test_cmpleu_sci_h(uint32_t a) {
	return __riscv_cv_simd_cmpleu_sc_h(a, 0);
}

// CHECK-LABEL: @test_cmpleu_sc_b
// CHECK: @llvm.riscv.cv.simd.cmpleu.sc.b
uint32_t test_cmpleu_sc_b(uint32_t a, uint8_t b) {
	return __riscv_cv_simd_cmpleu_sc_b(a, b);
}

// CHECK-LABEL: @test_cmpleu_sci_b
// CHECK: @llvm.riscv.cv.simd.cmpleu.sc.b
uint32_t test_cmpleu_sci_b(uint32_t a) {
	return __riscv_cv_simd_cmpleu_sc_b(a, 0);
}

// CHECK-LABEL: @test_cplxmul_r
// CHECK: @llvm.riscv.cv.simd.cplxmul.r
uint32_t test_cplxmul_r(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_cplxmul_r(a, b, c, 0);
}

// CHECK-LABEL: @test_cplxmul_i
// CHECK: @llvm.riscv.cv.simd.cplxmul.i
uint32_t test_cplxmul_i(uint32_t a, uint32_t b, uint32_t c) {
	return __riscv_cv_simd_cplxmul_i(a, b, c, 0);
}

// CHECK-LABEL: @test_cplxconj
// CHECK: @llvm.riscv.cv.simd.cplxconj
uint32_t test_cplxconj(uint32_t a) {
	return __riscv_cv_simd_cplxconj(a);
}

// CHECK-LABEL: @test_subrotmj
// CHECK: @llvm.riscv.cv.simd.subrotmj
uint32_t test_subrotmj(uint32_t a, uint32_t b) {
	return __riscv_cv_simd_subrotmj(a, b, 0);
}
